import type { Axis, MarkKind, StyleDef } from "@/lib/paint/types";

type StyleInit = {
  id: string;
  name: string;
  group: string;
  blurb: string;
  marks: { kind: MarkKind; w: number }[];
  alpha?: [number, number];
  size?: number;
  length?: number;
  hardness?: number;
  cover?: number;
  bleed?: number;
  drip?: number;
  bristles?: number;
  breakUp?: number;
  keyline?: number;
  axis?: Axis;
  spare?: boolean;
  allover?: boolean;
  pitchMap?: boolean;
  density?: number;
  echo?: number;
  reveal?: boolean;
  ground?: MarkKind;
};

function defineStyle(s: StyleInit): StyleDef {
  return {
    alpha: [0.55, 0.92],
    size: 1,
    length: 1,
    hardness: 0.55,
    cover: 0.75,
    bleed: 0.08,
    drip: 0,
    bristles: 5,
    breakUp: 0,
    keyline: 0,
    axis: "free",
    spare: false,
    allover: false,
    pitchMap: true,
    density: 1,
    echo: 0,
    reveal: false,
    ground: "wash",
    ...s,
  };
}

export const STYLE_GROUPS = ["Water", "Oil", "Opaque", "Ink", "Draw", "Print", "Street"] as const;

export const STYLES: StyleDef[] = [
  defineStyle({
    id: "watercolor",
    name: "Watercolor",
    group: "Water",
    blurb: "Translucent blooms, soft edges, pooling, and the occasional drip.",
    marks: [
      { kind: "wash", w: 5 },
      { kind: "pool", w: 3 },
      { kind: "stroke", w: 1 },
      { kind: "drip", w: 2 },
    ],
    alpha: [0.2, 0.46],
    size: 1.35,
    length: 1.2,
    hardness: 0.08,
    cover: 0.2,
    bleed: 0.85,
    drip: 0.5,
    density: 0.85,
    ground: "wash",
  }),
  defineStyle({
    id: "wet-on-wet",
    name: "Wet on wet",
    group: "Water",
    blurb: "Paint into paint that is still open. Edges melt.",
    marks: [
      { kind: "wash", w: 5 },
      { kind: "dab", w: 3 },
      { kind: "stroke", w: 2 },
    ],
    alpha: [0.28, 0.55],
    size: 1.2,
    hardness: 0.12,
    cover: 0.4,
    bleed: 0.7,
    ground: "wash",
  }),
  defineStyle({
    id: "glaze",
    name: "Glaze",
    group: "Water",
    blurb: "Thin luminous skins. The ground keeps showing through.",
    marks: [
      { kind: "glaze", w: 6 },
      { kind: "wash", w: 3 },
    ],
    alpha: [0.1, 0.24],
    size: 1.8,
    length: 1.45,
    hardness: 0.05,
    cover: 0.15,
    bleed: 0.45,
    density: 0.7,
    ground: "glaze",
  }),
  defineStyle({
    id: "acrylic-pour",
    name: "Acrylic pour",
    group: "Water",
    blurb: "Rivulets, pools, and gravity. The paint moves after the hand.",
    marks: [
      { kind: "streak", w: 3 },
      { kind: "wash", w: 4 },
      { kind: "pool", w: 3 },
      { kind: "drip", w: 3 },
    ],
    alpha: [0.45, 0.75],
    size: 1.25,
    hardness: 0.14,
    bleed: 0.6,
    drip: 0.9,
    ground: "wash",
  }),
  defineStyle({
    id: "dust",
    name: "Dust wash",
    group: "Water",
    blurb: "A veil. The form shows through the dirt.",
    marks: [
      { kind: "wash", w: 4 },
      { kind: "drybrush", w: 4 },
      { kind: "dot", w: 2 },
    ],
    alpha: [0.18, 0.4],
    size: 1.35,
    hardness: 0.12,
    cover: 0.28,
    bleed: 0.4,
    ground: "wash",
  }),
  defineStyle({
    id: "fresco",
    name: "Fresco",
    group: "Water",
    blurb: "Chalky and broad, like color sitting in plaster.",
    marks: [
      { kind: "wash", w: 3 },
      { kind: "drybrush", w: 4 },
      { kind: "block", w: 2 },
    ],
    alpha: [0.4, 0.72],
    hardness: 0.4,
    cover: 0.55,
    breakUp: 0.35,
    ground: "wash",
  }),
  defineStyle({
    id: "alla-prima",
    name: "Alla prima",
    group: "Oil",
    blurb: "Opaque dabs in one wet pass. The bristles stay in the paint.",
    marks: [
      { kind: "bristle", w: 6 },
      { kind: "dab", w: 3 },
      { kind: "stroke", w: 1 },
    ],
    alpha: [0.94, 1],
    size: 1.05,
    length: 0.68,
    hardness: 0.74,
    cover: 0.97,
    bristles: 7,
    ground: "bristle",
  }),
  defineStyle({
    id: "palette-knife",
    name: "Palette knife",
    group: "Oil",
    blurb: "Flat slabs. Hard edges. No blend, no bristle.",
    marks: [
      { kind: "knife", w: 8 },
      { kind: "block", w: 2 },
    ],
    alpha: [1, 1],
    size: 1.35,
    length: 0.9,
    hardness: 1,
    cover: 1,
    ground: "knife",
  }),
  defineStyle({
    id: "impasto",
    name: "Impasto",
    group: "Oil",
    blurb: "Paint thick enough to cast a ridge.",
    marks: [
      { kind: "bristle", w: 4 },
      { kind: "dab", w: 4 },
      { kind: "knife", w: 2 },
    ],
    alpha: [0.96, 1],
    size: 1.28,
    length: 0.72,
    hardness: 0.86,
    cover: 1,
    bristles: 8,
    ground: "dab",
  }),
  defineStyle({
    id: "bob-ross",
    name: "Wet fan",
    group: "Oil",
    blurb: "Soft fan dabs blended into a wet ground. Loaded, then tapped.",
    marks: [
      { kind: "dab", w: 5 },
      { kind: "stroke", w: 3 },
      { kind: "wash", w: 2 },
    ],
    alpha: [0.72, 0.95],
    size: 0.92,
    length: 0.78,
    hardness: 0.28,
    cover: 0.82,
    bleed: 0.28,
    bristles: 9,
    ground: "wash",
  }),
  defineStyle({
    id: "scumble",
    name: "Scumble",
    group: "Oil",
    blurb: "A dry light dragged over a darker body.",
    marks: [
      { kind: "drybrush", w: 6 },
      { kind: "glaze", w: 2 },
      { kind: "scratch", w: 1 },
    ],
    alpha: [0.28, 0.52],
    hardness: 0.58,
    cover: 0.35,
    breakUp: 0.7,
    ground: "drybrush",
  }),
  defineStyle({
    id: "encaustic",
    name: "Encaustic",
    group: "Oil",
    blurb: "Waxy slabs, a little translucent, fused at the edges.",
    marks: [
      { kind: "block", w: 3 },
      { kind: "glaze", w: 3 },
      { kind: "dab", w: 3 },
    ],
    alpha: [0.55, 0.86],
    hardness: 0.46,
    cover: 0.7,
    bleed: 0.22,
    ground: "block",
  }),
  defineStyle({
    id: "fingerpaint",
    name: "Fingerpaint",
    group: "Oil",
    blurb: "Blunt fingers. No fine line.",
    marks: [
      { kind: "dab", w: 6 },
      { kind: "wash", w: 2 },
      { kind: "stroke", w: 2 },
    ],
    alpha: [0.7, 0.95],
    size: 1.5,
    hardness: 0.34,
    cover: 0.78,
    bleed: 0.3,
    ground: "dab",
  }),
  defineStyle({
    id: "gouache",
    name: "Gouache",
    group: "Opaque",
    blurb: "Matte, flat, and covering. Light sits on top of dark.",
    marks: [
      { kind: "block", w: 4 },
      { kind: "dab", w: 4 },
      { kind: "stroke", w: 1 },
    ],
    alpha: [0.9, 1],
    hardness: 0.82,
    cover: 0.95,
    ground: "block",
  }),
  defineStyle({
    id: "tempera",
    name: "Tempera",
    group: "Opaque",
    blurb: "Flat decorative shapes with a thin dark contour.",
    marks: [
      { kind: "block", w: 4 },
      { kind: "outline", w: 3 },
      { kind: "dot", w: 2 },
    ],
    alpha: [0.9, 1],
    hardness: 0.9,
    cover: 0.9,
    keyline: 0.008,
    ground: "block",
  }),
  defineStyle({
    id: "oil-pastel",
    name: "Oil pastel",
    group: "Opaque",
    blurb: "Waxy, broken color. The paper tooth shows in the stroke.",
    marks: [
      { kind: "stroke", w: 4 },
      { kind: "dab", w: 3 },
      { kind: "drybrush", w: 3 },
    ],
    alpha: [0.75, 0.96],
    hardness: 0.6,
    cover: 0.8,
    breakUp: 0.48,
    ground: "drybrush",
  }),
  defineStyle({
    id: "marker",
    name: "Marker",
    group: "Opaque",
    blurb: "Flat bands with a streak where the ink ran thin.",
    marks: [
      { kind: "stroke", w: 6 },
      { kind: "block", w: 2 },
    ],
    alpha: [0.8, 0.96],
    size: 0.88,
    hardness: 0.86,
    cover: 0.9,
    breakUp: 0.14,
    ground: "stroke",
  }),
  defineStyle({
    id: "ink-wash",
    name: "Ink wash",
    group: "Ink",
    blurb: "High contrast, wet spread, and drips that run downhill.",
    marks: [
      { kind: "wash", w: 3 },
      { kind: "drip", w: 5 },
      { kind: "stroke", w: 3 },
      { kind: "splatter", w: 1 },
    ],
    alpha: [0.5, 0.92],
    size: 1.12,
    hardness: 0.36,
    cover: 0.72,
    bleed: 0.55,
    drip: 0.88,
    ground: "wash",
  }),
  defineStyle({
    id: "sumi",
    name: "Sumi-e",
    group: "Ink",
    blurb: "A few loaded strokes. Most of the sheet stays empty.",
    marks: [
      { kind: "stroke", w: 7 },
      { kind: "wash", w: 2 },
      { kind: "drip", w: 1 },
    ],
    alpha: [0.78, 1],
    size: 1.55,
    length: 1.5,
    hardness: 0.5,
    cover: 0.86,
    drip: 0.28,
    spare: true,
    density: 0.32,
    ground: "wash",
  }),
  defineStyle({
    id: "calligraphy",
    name: "Calligraphy",
    group: "Ink",
    blurb: "Pressure in the stroke. Thick, thin, then a tail.",
    marks: [
      { kind: "stroke", w: 8 },
      { kind: "drip", w: 2 },
    ],
    alpha: [0.88, 1],
    size: 0.82,
    length: 1.35,
    hardness: 0.62,
    drip: 0.32,
    spare: true,
    density: 0.45,
    ground: "stroke",
  }),
  defineStyle({
    id: "ink-stick",
    name: "Ink and stick",
    group: "Ink",
    blurb: "A stick dragged through ink. Dots where it hopped.",
    marks: [
      { kind: "stroke", w: 5 },
      { kind: "dot", w: 3 },
      { kind: "wash", w: 1 },
    ],
    alpha: [0.82, 1],
    size: 0.7,
    hardness: 0.62,
    ground: "stroke",
  }),
  defineStyle({
    id: "ballpoint",
    name: "Ballpoint",
    group: "Ink",
    blurb: "Dense hatching. The picture is built from pressure, not fill.",
    marks: [
      { kind: "hatch", w: 8 },
      { kind: "stroke", w: 3 },
    ],
    alpha: [0.55, 0.88],
    size: 0.55,
    length: 0.72,
    hardness: 0.95,
    cover: 0.65,
    breakUp: 0.16,
    density: 1.35,
    ground: "hatch",
  }),
  defineStyle({
    id: "art-nouveau",
    name: "Art nouveau",
    group: "Ink",
    blurb: "Whiplash curves and a clean contour.",
    marks: [
      { kind: "stroke", w: 5 },
      { kind: "outline", w: 4 },
      { kind: "dot", w: 1 },
    ],
    alpha: [0.86, 1],
    length: 1.25,
    hardness: 0.76,
    keyline: 0.006,
    ground: "stroke",
  }),
  defineStyle({
    id: "charcoal",
    name: "Charcoal",
    group: "Draw",
    blurb: "Smudged darks, a wiped highlight, soft dirty edges.",
    marks: [
      { kind: "drybrush", w: 4 },
      { kind: "wash", w: 4 },
      { kind: "scratch", w: 2 },
    ],
    alpha: [0.32, 0.68],
    hardness: 0.2,
    cover: 0.4,
    bleed: 0.35,
    breakUp: 0.42,
    ground: "wash",
  }),
  defineStyle({
    id: "conte",
    name: "Conte",
    group: "Draw",
    blurb: "A dry crayon. Grainy, warm, and a little harsh.",
    marks: [
      { kind: "drybrush", w: 5 },
      { kind: "hatch", w: 3 },
      { kind: "stroke", w: 2 },
    ],
    alpha: [0.62, 0.92],
    hardness: 0.5,
    cover: 0.7,
    breakUp: 0.42,
    ground: "drybrush",
  }),
  defineStyle({
    id: "pastel",
    name: "Pastel",
    group: "Draw",
    blurb: "Soft dust on tooth. Nothing is fully wet.",
    marks: [
      { kind: "drybrush", w: 5 },
      { kind: "stroke", w: 2 },
      { kind: "hatch", w: 2 },
      { kind: "dot", w: 1 },
    ],
    alpha: [0.45, 0.78],
    hardness: 0.22,
    cover: 0.5,
    bleed: 0.16,
    breakUp: 0.55,
    ground: "drybrush",
  }),
  defineStyle({
    id: "pencil",
    name: "Colored pencil",
    group: "Draw",
    blurb: "Hatched, layered, and a little scratchy.",
    marks: [
      { kind: "hatch", w: 7 },
      { kind: "stroke", w: 2 },
    ],
    alpha: [0.48, 0.82],
    size: 0.6,
    hardness: 0.88,
    cover: 0.6,
    breakUp: 0.2,
    density: 1.25,
    ground: "hatch",
  }),
  defineStyle({
    id: "scratchboard",
    name: "Scratchboard",
    group: "Draw",
    blurb: "A dark field opened with light scratches.",
    marks: [
      { kind: "scratch", w: 7 },
      { kind: "stroke", w: 2 },
      { kind: "block", w: 1 },
    ],
    alpha: [0.92, 1],
    hardness: 1,
    cover: 1,
    reveal: true,
    density: 1.15,
    ground: "block",
  }),
  defineStyle({
    id: "sgraffito",
    name: "Sgraffito",
    group: "Draw",
    blurb: "Scraped back through a coat of paint.",
    marks: [
      { kind: "knife", w: 2 },
      { kind: "scratch", w: 6 },
      { kind: "stroke", w: 2 },
    ],
    alpha: [0.75, 1],
    hardness: 0.82,
    cover: 0.75,
    ground: "knife",
  }),
  defineStyle({
    id: "pointillism",
    name: "Pointillism",
    group: "Draw",
    blurb: "Only dots. The form arrives when you lean back.",
    marks: [{ kind: "dot", w: 10 }],
    alpha: [0.88, 1],
    size: 0.72,
    hardness: 1,
    cover: 0.92,
    density: 1.55,
    ground: "dot",
  }),
  defineStyle({
    id: "stipple",
    name: "Stipple",
    group: "Draw",
    blurb: "A tighter dot, more drawing than mosaic.",
    marks: [
      { kind: "dot", w: 8 },
      { kind: "hatch", w: 1 },
    ],
    alpha: [0.7, 0.95],
    size: 0.46,
    hardness: 0.92,
    density: 1.4,
    ground: "dot",
  }),
  defineStyle({
    id: "crosshatch",
    name: "Crosshatch",
    group: "Draw",
    blurb: "Parallel families of lines. Value is how close they sit.",
    marks: [
      { kind: "hatch", w: 8 },
      { kind: "stroke", w: 2 },
    ],
    alpha: [0.55, 0.88],
    size: 0.8,
    hardness: 0.9,
    ground: "hatch",
  }),
  defineStyle({
    id: "drybrush",
    name: "Dry brush",
    group: "Draw",
    blurb: "A starved brush. The stroke breaks on the tooth.",
    marks: [
      { kind: "drybrush", w: 8 },
      { kind: "scratch", w: 2 },
    ],
    alpha: [0.58, 0.92],
    hardness: 0.66,
    cover: 0.6,
    breakUp: 0.78,
    ground: "drybrush",
  }),
  defineStyle({
    id: "comic",
    name: "Comic book",
    group: "Print",
    blurb: "Flat color, a heavy keyline, halftone in the shadow.",
    marks: [
      { kind: "block", w: 4 },
      { kind: "outline", w: 5 },
      { kind: "halftone", w: 3 },
    ],
    alpha: [0.96, 1],
    hardness: 1,
    cover: 1,
    keyline: 0.012,
    ground: "block",
  }),
  defineStyle({
    id: "woodblock",
    name: "Woodblock",
    group: "Print",
    blurb: "Flat shapes and a key line, registered a hair off.",
    marks: [
      { kind: "block", w: 5 },
      { kind: "outline", w: 4 },
    ],
    alpha: [1, 1],
    hardness: 1,
    cover: 1,
    keyline: 0.01,
    echo: 0.012,
    ground: "block",
  }),
  defineStyle({
    id: "linocut",
    name: "Linocut",
    group: "Print",
    blurb: "Gouged and high contrast. The cut is the drawing.",
    marks: [
      { kind: "block", w: 5 },
      { kind: "scratch", w: 3 },
      { kind: "outline", w: 2 },
    ],
    alpha: [1, 1],
    hardness: 1,
    cover: 1,
    keyline: 0.011,
    ground: "block",
  }),
  defineStyle({
    id: "screenprint",
    name: "Screen print",
    group: "Print",
    blurb: "Flat passes, a little halftone, a misregistered second hit.",
    marks: [
      { kind: "block", w: 6 },
      { kind: "halftone", w: 2 },
    ],
    alpha: [1, 1],
    hardness: 1,
    cover: 1,
    echo: 0.014,
    ground: "block",
  }),
  defineStyle({
    id: "collage",
    name: "Collage",
    group: "Print",
    blurb: "Hard-edged scraps dropped on the sheet.",
    marks: [
      { kind: "block", w: 7 },
      { kind: "stroke", w: 1 },
    ],
    alpha: [1, 1],
    size: 1.4,
    length: 0.55,
    hardness: 1,
    cover: 1,
    ground: "block",
  }),
  defineStyle({
    id: "roller",
    name: "Roller",
    group: "Print",
    blurb: "A loaded roller. Bands, skips, and a hard stop.",
    marks: [
      { kind: "block", w: 4 },
      { kind: "streak", w: 3 },
      { kind: "drybrush", w: 2 },
    ],
    alpha: [0.72, 0.95],
    size: 1.2,
    length: 1.15,
    hardness: 0.76,
    cover: 0.82,
    breakUp: 0.28,
    axis: "horiz",
    ground: "block",
  }),
  defineStyle({
    id: "spray",
    name: "Spray",
    group: "Street",
    blurb: "Overspray, drips, and a soft stencil edge.",
    marks: [
      { kind: "splatter", w: 5 },
      { kind: "streak", w: 4 },
      { kind: "drip", w: 3 },
      { kind: "dot", w: 2 },
    ],
    alpha: [0.55, 0.88],
    size: 1.1,
    hardness: 0.25,
    drip: 0.55,
    ground: "splatter",
  }),
  defineStyle({
    id: "stencil",
    name: "Stencil",
    group: "Street",
    blurb: "A hard mask with paint creeping past the edge.",
    marks: [
      { kind: "block", w: 5 },
      { kind: "splatter", w: 3 },
      { kind: "outline", w: 1 },
    ],
    alpha: [0.82, 1],
    hardness: 1,
    cover: 0.95,
    drip: 0.25,
    ground: "block",
  }),
  defineStyle({
    id: "graffiti",
    name: "Graffiti",
    group: "Street",
    blurb: "Long kinetic sprays and drips running off the form.",
    marks: [
      { kind: "streak", w: 4 },
      { kind: "drip", w: 4 },
      { kind: "splatter", w: 3 },
      { kind: "outline", w: 2 },
    ],
    alpha: [0.8, 1],
    length: 1.2,
    hardness: 0.45,
    drip: 0.72,
    ground: "streak",
  }),
  defineStyle({
    id: "neon-tube",
    name: "Neon tube",
    group: "Street",
    blurb: "A thin bright core and a halo that blooms off it.",
    marks: [
      { kind: "stroke", w: 6 },
      { kind: "wash", w: 3 },
      { kind: "outline", w: 1 },
    ],
    alpha: [0.9, 1],
    size: 0.55,
    length: 1.15,
    hardness: 0.16,
    bleed: 0.85,
    ground: "wash",
  }),
  defineStyle({
    id: "airbrush",
    name: "Airbrush",
    group: "Street",
    blurb: "Seamless gradients. Almost no edge at all.",
    marks: [
      { kind: "wash", w: 8 },
      { kind: "streak", w: 2 },
    ],
    alpha: [0.16, 0.4],
    size: 1.55,
    hardness: 0.02,
    cover: 0.25,
    bleed: 0.92,
    ground: "wash",
  }),
  defineStyle({
    id: "pollock",
    name: "All-over drip",
    group: "Street",
    blurb: "Flung paint across the whole sheet. The subject sits underneath.",
    marks: [
      { kind: "splatter", w: 6 },
      { kind: "drip", w: 5 },
      { kind: "streak", w: 2 },
    ],
    alpha: [0.78, 1],
    size: 0.8,
    hardness: 0.7,
    drip: 0.78,
    allover: true,
    density: 1.7,
    ground: "splatter",
  }),
  defineStyle({
    id: "fauve",
    name: "Fauve",
    group: "Street",
    blurb: "Color chosen for heat, not for the note. Still inside the palette.",
    marks: [
      { kind: "dab", w: 5 },
      { kind: "stroke", w: 4 },
      { kind: "block", w: 1 },
    ],
    alpha: [0.9, 1],
    size: 1.15,
    hardness: 0.8,
    cover: 0.92,
    pitchMap: false,
    ground: "dab",
  }),
  defineStyle({
    id: "slash",
    name: "Slash",
    group: "Street",
    blurb: "Diagonal cuts. The arm, not the wrist.",
    marks: [
      { kind: "stroke", w: 8 },
      { kind: "drybrush", w: 2 },
    ],
    alpha: [0.86, 1],
    size: 0.9,
    length: 1.4,
    hardness: 0.72,
    cover: 0.88,
    axis: "diag",
    ground: "stroke",
  }),
  defineStyle({
    id: "automatism",
    name: "Automatism",
    group: "Street",
    blurb: "The hand moving faster than the plan.",
    marks: [
      { kind: "stroke", w: 4 },
      { kind: "splatter", w: 3 },
      { kind: "scratch", w: 2 },
      { kind: "drip", w: 1 },
    ],
    alpha: [0.55, 0.9],
    hardness: 0.4,
    drip: 0.3,
    allover: true,
    density: 1.2,
    ground: "stroke",
  }),
  defineStyle({
    id: "sponge",
    name: "Sponge",
    group: "Street",
    blurb: "Dabbed texture. Stippled, not stroked.",
    marks: [
      { kind: "splatter", w: 4 },
      { kind: "dot", w: 4 },
      { kind: "dab", w: 2 },
    ],
    alpha: [0.4, 0.72],
    size: 1.1,
    hardness: 0.3,
    breakUp: 0.5,
    ground: "splatter",
  }),
  defineStyle({
    id: "mixed",
    name: "Mixed media",
    group: "Street",
    blurb: "Knife, wash, hatch, splatter, scrap. The playing picks the tool.",
    marks: [
      { kind: "knife", w: 2 },
      { kind: "wash", w: 2 },
      { kind: "hatch", w: 2 },
      { kind: "splatter", w: 2 },
      { kind: "block", w: 2 },
    ],
    alpha: [0.62, 0.96],
    hardness: 0.6,
    cover: 0.75,
    drip: 0.22,
    density: 1.15,
    ground: "wash",
  }),
];

export function styleById(id: string) {
  return STYLES.find((s) => s.id === id) ?? STYLES[0];
}
